name: build preview image

on:
    push:
        branches:
            - main

jobs:
    push_to_registry:
        name: build & push image
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Include version number
              run: echo "PREVIEW-${{ github.run_number }}" > version.txt
            - name: Push to GitHub Packages
              uses: docker/build-push-action@v2
              with:
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: wahlrechner/wahlrechner/wahlrechner-preview
                  tags: latest, PREVIEW-${{ github.run_number }}
